### ISSUE TITLE
Google Forms and browser compatibility

### ISSUE THREAD

**Issue by angelsubirana** [TimOliver/TOWebViewController#110]
Hi, 

I am using this library with iOS 10.2. When I try to open an url from Google Forms, Google detects it as an old browser and shows the following warning in top of the webpage...

"The version of the browser you are using is no longer supported. Please upgrade to a supported browser."

Following the link in the warning, it explains that a browser of iOS 8 or above is required, but for whatever reason it is not able to correctly detect TOWebViewController webview version. Anyone else faced the same issue?

For example, I have created the following Google Form in order to test:

https://goo.gl/forms/XIfOLtLB9mSeHZ0p2

So far, what I have tried is to force the User-Agent in the urlRequest of the TOWebViewController to an user agent of iOS 10 Safari but without any luck. Any ideas or suggestions?

Best Regards,

**Comment by TimOliver** [comment]
Hi there @angelsubirana!

Hmm, I just tried your link in the iOS Simulator running iOS 10.3 and it looked fine to me.

![simulator screen shot may 1 2017 1 04 12 pm](https://cloud.githubusercontent.com/assets/429119/25592757/cf22af1a-2e6e-11e7-9c0b-6749a8d47019.png)

Where was the message appearing for you? Can you send a screenshot?

I probably should preface this by saying that since `TOWebViewController` uses `UIWebView` to remain compatible with iOS versions below 8, it's definitely a bit old at this point.

Time permitting, I want to do a complete rewrite with `WKWebView` at some point. :)

**Comment by angelsubirana** [comment]
Hi Tim,

I have just done a test with iOS 10.3 and 9.3 and now the message I was talking about some time ago does not appear in Google forms. So apparently the problem was with some wrong check in Google side (maybe the browser user-agent I dont know...), but as you stated now the webpage is showing without any warning. So from my side this "issue" can be closed.

Thanks for your support!
