### ISSUE TITLE
XCode 8.3 warnings

### ISSUE THREAD

**Issue by ranhsd** [TimOliver/TOWebViewController#112]
Hi, after updating XCode the the latest version i am getting the following warning

<img width="346" alt="screen shot 2017-05-01 at 13 45 51" src="https://cloud.githubusercontent.com/assets/3685671/25578152/869b26c2-2e74-11e7-8fda-620f76329a59.png">

Can you please fix it?

Thanks!

**Comment by TimOliver** [comment]
Hi @ranhsd! Thanks for the issue, but next time please be sure to fill out the issue template and not just delete it. :)

IIRC, this is happening because I was passing `nil` to an animation delegate that later required a value when Objective-C brought out `nullable` / `nonnull` properties. Since the receiving object is the same view controller, there's no chance of this causing any issues with the system (*touch wood*).

It can probably just be suppressed with a `#pragma` statement. I'm sadly very busy at the moment, so it'd be mighty great if you could fix it and file a PR yourself. :)

Thanks!

**Comment by TimOliver** [comment]
This looks like it solved! Thanks for the issue!
