### ISSUE TITLE
load automatically fin view controller

### ISSUE THREAD

**Issue by qquestel** [TimOliver/TOWebViewController#70]
Hi... I am having a little problem as i am new to this. I simply want to hardcode the url in a view controller and when i access the view controller it loads the url automatically. I don't want to have a page before with a tableview that when i click the page loads.

How do i do this?

**Comment by TimOliver** [comment]
Hi there!

That table view section is just part of the demo app. You don't need to bring that part over to your own project.

In order to install `TOWebViewController` into your app, all you have to do is drag the 'TOWebViewController' folder (That contains the TOWebViewController class files) into your app. After that, you can use the example app provided to see exactly how to make this controller appear in your own app.

Good luck!

**Comment by qquestel** [comment]
still confused... do i need to put the following in my app delegate file? And the hardcoded url exist in the TOViewController with the table... How do i move so it is simply a view

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    //Create the main window
    self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    
    self.viewController = [[TOViewController alloc] init];

    //Push to a navigation controller
    self.navController = [[UINavigationController alloc] initWithRootViewController:self.viewController];
    
    //present on screen
    self.window.rootViewController = self.navController;
    [self.window makeKeyAndVisible];
    
    return YES;
}
